# Welcome to Serverless!
#
# For full config options, check the kubeless plugin docs:
#    https://github.com/serverless/serverless-kubeless
#
# For documentation on kubeless itself:
#    http://kubeless.io

# Update the service name below with your own service name
service: kumuless

# Please ensure the serverless-kubeless provider plugin is installed globally.
# $ npm install -g serverless-kubeless
#
# ...before installing project dependencies to register this provider.
# $ npm install

provider:
  name: kubeless
  runtime: python3.7
  deploy:
    strategy: S3ZipContent
    options:
      accessKeyId: 73BJMITDA739XC4M54SK
      secretAccessKey: gCO1Xh+qJGWVbODIKC3eZ5qVHTvxpZ64K8D9pGv6
      endpoint: http://localhost:9000
      region: us-east-1
      bucket: kumuless
      s3ForcePathStyle: true
plugins:
  - serverless-kubeless
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  hello:
    handler: handler.hello

# References
# [1] https://serverless.com/framework/docs/providers/kubeless/guide/deploying/